In [1]:
import numpy as np
x=np.array([1,2,3,4])

In [2]:
x

array([1, 2, 3, 4])

In [3]:
x[2]

3

In [8]:
y=np.ones((5,5))

In [9]:
y

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
y[1:3:1,1:3]=0

In [16]:
y

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 1., 1.],
       [1., 0., 0., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
y[::,3:5]

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [18]:
y[::,3:5]=5

In [19]:
y

array([[1., 1., 1., 5., 5.],
       [1., 0., 0., 5., 5.],
       [1., 0., 0., 5., 5.],
       [1., 1., 1., 5., 5.],
       [1., 1., 1., 5., 5.]])