In [1]:
import numpy as np

In [2]:
a=np.random((10))

TypeError: 'module' object is not callable

In [7]:
a=np.random.randn(10)

In [8]:
a

array([-0.41823861, -0.87767638,  1.25596553,  0.1521562 ,  0.23257845,
       -0.21970063,  0.96188555, -0.10468601,  1.54138161,  0.21852511])

In [10]:
import numpy.random as npr

In [11]:
b=npr.randn(10)

In [12]:
c=npr.randn(10)

In [13]:
b*c

array([ 0.07988317, -0.55155172, -0.11717613,  0.82356404,  0.24765328,
        0.98515777,  1.52570794,  1.2989369 ,  2.6789252 , -0.20220716])

In [14]:
b-c


array([-0.23207607, -1.69700445,  0.87489388,  1.00736729, -0.19094011,
       -0.25857782, -1.06953501,  0.89954656,  0.00457118,  0.93912548])

In [15]:
b-a

array([-0.00332847, -0.38119678, -0.54615176, -0.68638453, -0.83477112,
       -0.91052454, -2.84264126, -0.67078881, -3.17583987,  0.11582666])

In [16]:
a>0

array([False, False,  True,  True,  True, False,  True, False,  True,
        True])

In [19]:
if(a>0):
    a

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [20]:
a[a>0]

array([1.25596553, 0.1521562 , 0.23257845, 0.96188555, 1.54138161,
       0.21852511])

In [21]:
a[5]

-0.21970062642004537

In [22]:
d=np.array([1,2,3])

In [23]:
d*2

array([2, 4, 6])

In [24]:
d[2]

3

In [25]:
d[1]*2

4